# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: HA MIN JEONG (정하민)
title: Product Engineer (iOS, Flutter)
email: solverjhm@gmail.com
phone: 010-9465-9404 
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: wjdgkals23
instagram_username: solver_hamin

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Hello!
about_profile_image: 
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. Product Engineer 정하민입니다.

  엔지니어링은 저에게 스타트업 생태계에서 다양한 사람들과 함께 문제해결의 기회를 준 고마운 도구입니다. 

  현재는 모바일 엔지니어링(iOS, Flutter)을 통해 다양한 분들과 문제 해결의 경험을 쌓아가고 있습니다.

  문제 해결 역량을 키우기 위해서는 다양한 경험과 도구들이 필요로 합니다.

  팀과 함께 해결하고 싶은 문제해결에 도움이 될 수 있다면, 엔지니어링 이외의 영역에도 도전하여 “어떤 문제가 찾아와도 두려워하지 않는 사람”이 되고자 합니다.

content:
  - title: About Me # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 성향
        description: | # this will include new lines to allow paragraphs
          - 학습과 병행하며 결과물을 만드는 상황에서 가장 많이 성장합니다.
          - 실패에 개의치않으며, 다음을 생각합니다.
          - 피드백 주기가 짧은 것을 좋아합니다.
          - 개인의 선택과 집중을 위해 목표 관리 도구(Jira, Notion)를 활용합니다.
          - 25분 업무, 5분 휴식의 형태로 업무를 수행합니다.
          - 오피스에서 집중력이 더 높습니다.
          - 조직에 목표가 없는 상황과 팀 목표에 도움되지 않는 업무 수행을 힘들어합니다.
          - 논의 시 배경에 대한 설명이 부족한 경우가 있으며, 이를 위해 팀원들에게 설명한 내용 중 부족한 것이 없는지 지속적으로 확인합니다.
      - layout: left
        title: 협업
        description: | # this will include new lines to allow paragraphs
          - 기본적인 Git Flow를 이해하고 있으며 필요한 동작을 찾고 적용할 수 있습니다.
          - 팀의 선택과 집중을 위해 목표 관리 도구(Jira, Notion)를 활용합니다.
          - 복수의 인원이 반복적으로 수행하는 작업은 문서화합니다.
          - Figma를 통한 디자인 협업이 가능합니다.
      - layout: left
        title: Engineering > iOS
        description: | # this will include new lines to allow paragraphs
          - Swift의 기본적인 이해를 토대로 협업을 위한 코드를 작성할 수 있습니다.
          - MVVM을 다양한 방식으로 구현할 수 있으며 Input/Output을 명확하게 구분하는 코드를 선호합니다.
          - UIKit과 AutoLayout을 통해 목적에 부합하는 화면을 구현할 수 있습니다.
          - Network를 설정할 수 있습니다.
          - 테스트 코드를 정의하고 작성할 수 있습니다.
          - Dependency Graph를 이해하고 있으며, Cocoapod / SPM 등을 통해 Dependency를 관리할 수 있습니다.
          - xcconfig를 통해 간단하게 배포 관련 설정값을 관리할 수 있습니다.
          - fastlane을 통해 iOS 개발 인증서 및 프로필을 관리, 자동화 배포를 설계할 수 있습니다.
  - title: Work Experience
    layout: list
    content:
      - layout: top-middle
        title: 뱅크샐러드 (Banksalad)
      - layout: left
        sub_title: User Experience Strategy Team
        caption: iOS Engineer 2021.07 ~  
        description: | # this will include new lines to allow paragraphs
          제품 구성에 대한 가설을 검증하며 고객 리텐션에 집중하는 사용자 경험 전략 팀의 iOS Engineer로 활동하는 중입니다.
          - 조직 목표 달성 및 고객 리텐션 강화를 위한 어플리케이션 개편 수행
          - 투자 제품 기여 (청약 알림/가점 계산, 주식 평단가 공개 커뮤니티)
          - 팀 스프린트 관리, 회고 문화 구성
      - layout: left
        sub_title: iOS Foundation
        caption: iOS Engineer 2021.04 ~ 2020.06
        description: | # this will include new lines to allow paragraphs
          iOS Core 팀으로 제품 개발을 수행에 필수적인 iOS 업데이트 대응과 배포개선을 수행했습니다.
          - iOS 14.5 보안 및 마케팅 대응설계
          - [Jenkins Distribution Job 코드화 개선](https://jhmdevdiary.tistory.com/30)
      - layout: left
        sub_title: Data Instrumentation Team
        caption: iOS Engineer 2021.01 ~ 2021.04
        description: | # this will include new lines to allow paragraphs
          데이터를 기반으로 제품 개발을 수행하는 팀의 iOS Engineer로 활약하였습니다.
          - iOS 프로젝트 A/B Testing 환경 개편
          - 테이터 기반 제품 개발수행
      - layout: left
        sub_title: iOS Foundation
        caption: iOS Engineer 2020.02 ~ 2020.12
        description: | # this will include new lines to allow paragraphs
          iOS Core 팀으로 제품 개발을 수행하는 iOS Engineer들의 효율성을 높였습니다.
          - Design System 개발 기여
          - 어플리케이션 개편 수행
          - 어플리케이션 AU Event 개선 설계
          - iOS 프로젝트 내의 협업툴(개발자도구) 설계
          - iOS 프로젝트 목적별 배포 설계 (xcconfig, Fastlane)
      - layout: top-middle
        title: PAYBOOC (브이피) 
      - layout: left
        sub_title: 결제 인증개발팀
        caption: iOS Engineer 2019.02 ~ 2020.01
        description: | # this will include new lines to allow paragraphs
          BC,KB 카드 결제인증 IOS APP인 PAYBOOC을 유지보수 하였으며, 신규 서비스를 추가하는 역할을 담당하였습니다.
  - title: 기타활동
    layout: list
    content:
      - layout: left
        title: 잇다 멘토링 활동
        description: | 
          목표를 가지고 있는 엔지니어와 협업하는 것을 선호합니다. 목표에 대한 중요성을 공유하며 더 많은 분들이 목표를 가진 엔지니어가 되기를 희망하며 멘토링을 하고 있습니다.
          
          <a href="https://www.itdaa.net/mentors/122067">프로필</a>
      - layout: left
        title: 논문 활동
        description: |
          KCI 논문 (2018)
          - [딥 러닝 기반 이미지 자동 분류 및 랭킹 시스템을 이용한 사용자 편의중심의 유실물 등록 및 조회 관리 시스템](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002401814)
          - [효율적인 사물 이미지 분류를 위한계층적 이미지 분류 체계의 설계 및 구현](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002393794)
      - layout: left
        title: 블로깅/개인공부
        layout: text
        description: |
          [개발 블로그](https://jhmdevdiary.tistory.com)

          개인 공부 글 모음
            - [Swift](https://devdmbhm.notion.site/SwiftInDepth-2e717661642249c7813b72769974be24)
            - [RxSwift](https://devdmbhm.notion.site/RxSwift-d468b63295bd4f888b575c1667e1f485)
            - [SwiftUI](https://devdmbhm.notion.site/SwiftUI-9b87bbce2c6b4ee5b04b60acfbef5a93)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
