# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: HA MIN JEONG (정하민)
title: Software Engineer (iOS)
email: solverjhm@gmail.com
# email_title: Email (Email title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  wjdgkals23
instagram_username: solver_hamin

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 정하민입니다.

  제가 현재 iOS 엔지니어로 활동하는 이유는 문제를 해결하는 스타트업 생태계에 참여할 수 있는 기회를 주기 때문입니다.
  
  지금은 iOS 엔지니어링이라는 무기 하나를 들고있지만, 스타트업 생태계에서 경험을 쌓아가며 문제해결에 필요한 많은 무기를 얻고자합니다.
  
  최근에는 iOS 엔지니어링과 회고 활동,지라를 학습하며 팀의 성장과 프로세스 개선에 시간을 투자하고 있습니다.

  
  제가 가장 좋아하는 문장은 **"실수는 예방하는 것이 아니라 관리하는 것이며, 실수를 통한 학습에서 성장한다"** 입니다.

content:
  - title: Ability # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: iOS
        description: | # this will include new lines to allow paragraphs
          - UIKit과 AutoLayout에 대한 개념을 이해하고 있고 팀의 목적에 부합하는 화면을 구현할 수 있습니다.
          - URLSession을 이해하고 있으며, 프로젝트에서는 Moya/Rxswift를 통해 Network를 편리하게 설정할 수 있습니다.
          - Swift의 기본적인 이해와 Instrument/Xcode 도구를 통하여 Memory Leak을 예방 및 개선하며 협업을 위한 코드를 작성할 수 있습니다.
          - MVVM을 다양한 방식으로 구현할 수 있으며 그중에서도 RxSwift를 통해 Input/Output을 명확하게 구분하는 코드를 작성할 수 있습니다.
          - 코드에 대한 자신감을 위한 테스트 코드를 정의하고 작성할 수 있습니다.
      - layout: left
        title: iOS DevOps
        description: | # this will include new lines to allow paragraphs
          - Dependency Graph를 이해하고 있으며, Cocoapod / SPM 등을 통해 Dependency를 관리할 수 있습니다.
          - xcconfig를 통해 간단하게 배포 관련 설정값을 관리할 수 있습니다.
          - fastlane을 통해 iOS 개발 인증서 및 프로젝트 프로필을 관리할 수 있습니다.
          - Jenkins Pipeline을 이용한 배포라인을 개편한 [경험](https://jhmdevdiary.tistory.com/30)을 가지고 있습니다.
          - Apple의 EnterPrise 인증서를 적용한 경험이 있습니다.
      - layout: left
        title: 협업
        description: | # this will include new lines to allow paragraphs
          - 기본적인 Git Flow를 이해하고 있으며 필요한 동작을 찾고 적용할 수 있습니다.
          - 모든 작업에 대해 문서를 만드는 것을 선호합니다.
          - Jira를 통한 스프린트 일정 관리가 가능하며, 팀 회고를 리드한 경험을 가지고 있습니다.
          - Figma를 통한 디자인 협업에 능숙하며, 프로토타입을 위한 간단한 화면 디자인을 만든 경험이 있습니다.
  - title: Work Experience
    layout: list
    content:
      - layout: top-middle
        title: 뱅크샐러드 (Banksalad)
      - layout: left
        sub_title: User Experience Strategy Team
        caption: iOS Engineer 2021.07 ~  
        description: | # this will include new lines to allow paragraphs
          제품 VOC 및 고객의 데이터를 기반으로 도출한 제품 구성에 대한 가설을 검증하는 사용자 경험 전략 팀의 iOS Engineer로 활동하고 있습니다.
          - [단독 어플리케이션 개편](https://www.instagram.com/p/CS84rfjL-5Z/?utm_medium=copy_link)
          - 제품 배포전략 수립을 위한 앱 구조 개편설계
      - layout: left
        sub_title: iOS Foundation
        caption: iOS Engineer 2021.04 ~ 2020.06
        description: | # this will include new lines to allow paragraphs
          iOS Core 팀으로 제품 개발을 수행하는 iOS Engineer들의 효율성을 높였습니다.
          - iOS 14.5 보안 및 마케팅 대응설계
          - [Jenkins Distribution Job 코드화 개선](https://jhmdevdiary.tistory.com/30)
      - layout: left
        sub_title: Data Instrumentation Team
        caption: iOS Engineer 2021.01 ~ 2021.04
        description: | # this will include new lines to allow paragraphs
          조직 내에서 고객의 데이터를 기반으로 제품 개발을 수행하며 A/B Testing 사용의 Best Practice를 만들어가는 팀의 iOS Engineer로 활약하였습니다.
          - iOS 프로젝트 사내 A/B Testing 환경 개편설계
          - A/B Testing 기반 제품 개발수행
      - layout: left
        sub_title: iOS Foundation
        caption: iOS Engineer 2020.02 ~ 2020.12
        description: | # this will include new lines to allow paragraphs
          iOS Core 팀으로 제품 개발을 수행하는 iOS Engineer들의 효율성을 높였습니다.
          - Design System 개발 기여
          - 어플리케이션 개편 수행
          - 어플리케이션 AU Event 개선 설계
          - iOS 프로젝트 내의 협업툴(개발자도구) 설계
          - iOS 프로젝트 목적별 배포 설계 (xcconfig, Fastlane)
      - layout: top-middle
        title: PAYBOOC (브이피) 
      - layout: left
        sub_title: 결제 인증개발팀
        caption: iOS Engineer 2019.02 ~ 2020.01
        description: | # this will include new lines to allow paragraphs
          BC,KB 카드 결제인증 IOS APP인 PAYBOOC을 유지보수 하였으며, 신규 서비스를 추가하는 역할을 담당하였습니다.
  - title: 기타활동
    layout: list
    content:
      - layout: left
        title: 잇다 멘토링 활동
        description: | 
          목표를 가지고 있는 엔지니어와 협업하는 것은 환상적인 경험입니다!
          
          제가 시작할 때 가졌으면 좋았을 생각을 조금이라도 더 빨리 많은 분들에게 전달하는 것이 목표이며, 그로 인해 많은 예비 엔지니어 분들이 목표를 꿈꾸길 바라며 멘토링을 하고 있습니다.
          <a href="https://www.itdaa.net/mentors/122067">프로필</a>
      - layout: left
        title: 논문 활동
        description: |
          KCI 논문 (2018)
          - [딥 러닝 기반 이미지 자동 분류 및 랭킹 시스템을 이용한 사용자 편의중심의 유실물 등록 및 조회 관리 시스템](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002401814)
          - [효율적인 사물 이미지 분류를 위한계층적 이미지 분류 체계의 설계 및 구현](https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART002393794)
      - layout: left
        title: 블로깅/개인공부
        layout: text
        description: |
          [개발 블로그](https://jhmdevdiary.tistory.com)

          개인 공부 글 모음
            - [Swift](https://devdmbhm.notion.site/SwiftInDepth-2e717661642249c7813b72769974be24)
            - [RxSwift](https://devdmbhm.notion.site/RxSwift-d468b63295bd4f888b575c1667e1f485)
            - [SwiftUI](https://devdmbhm.notion.site/SwiftUI-9b87bbce2c6b4ee5b04b60acfbef5a93)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
